# Generated by Django 6.0 on 2026-04-30 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('physics', 'Physics'), ('astronomy', 'Astronomy'), ('problems', 'Problems'), ('general', 'General Space')], default='general', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('question', models.TextField(help_text='Question text (Uzbek)')),
                ('question_en', models.TextField(blank=True, default='')),
                ('question_ru', models.TextField(blank=True, default='')),
                ('options', models.JSONField(help_text='List of 4 answer options')),
                ('correct_answer', models.PositiveSmallIntegerField(help_text='0-based index of correct option')),
                ('explanation', models.TextField(blank=True, default='', help_text='Why this answer is correct')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Challenge Question',
                'ordering': ['category', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('question_count', models.PositiveSmallIntegerField(default=5)),
                ('time_limit', models.PositiveSmallIntegerField(default=15, help_text='Seconds per question')),
                ('xp_per_correct', models.PositiveIntegerField(default=50)),
                ('xp_completion_bonus', models.PositiveIntegerField(default=100)),
                ('fuel_reward', models.PositiveIntegerField(default=20, help_text='Fuel reward for completing')),
                ('is_active', models.BooleanField(default=True)),
                ('questions', models.ManyToManyField(related_name='daily_challenges', to='challenges.challengequestion')),
            ],
            options={
                'verbose_name': 'Daily Challenge',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_completed', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Streak',
            },
        ),
        migrations.CreateModel(
            name='UserChallengeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='Number of correct answers')),
                ('total', models.PositiveSmallIntegerField(default=5)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('fuel_earned', models.PositiveIntegerField(default=0)),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='Total seconds taken')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='challenges.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge Result',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
