# Generated by Django 6.0 on 2026-04-30 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challengequestion',
            name='time_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Time limit per question in seconds'),
        ),
        migrations.AlterField(
            model_name='challengequestion',
            name='category',
            field=models.CharField(choices=[('physics', 'Physics'), ('astronomy', 'Astronomy'), ('problems', 'Problems'), ('courses', 'Online Courses'), ('general', 'General Space')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('physics', 'Physics'), ('astronomy', 'Astronomy'), ('problems', 'Problems'), ('courses', 'Online Courses')], max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='Total seconds')),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('questions', models.ManyToManyField(related_name='quiz_sessions', to='challenges.challengequestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.IntegerField(help_text='0-based index selected by user')),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Seconds spent on this question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challengequestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='challenges.quizsession')),
            ],
            options={
                'verbose_name': 'Quiz Answer',
                'ordering': ['id'],
            },
        ),
    ]
