# Generated by Django 6.0 on 2026-08-22 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challengequestion_time_seconds_and_more'),
        ('courses', '0004_adr0001_slug_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengequestion',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Attach this question to one lesson. Empty means it is only in the category pool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='courses.topiclesson'),
        ),
    ]
