import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'base.settings')
django.setup()

from apps.gamification.models import RewardProduct

products = [
    {
        'slug': 'space-run-shield-pack',
        'title_en': 'Space Run: Shield Pack',
        'title_uz': 'Space Run: Qalqon Paketi',
        'title_ru': 'Space Run: Набор Щитов',
        'description_en': 'Start every Space Run session with a full shield. Survive longer, earn more stars and XP.',
        'description_uz': "Har bir Space Run sessiyasini to'liq qalqon bilan boshlang.",
        'description_ru': 'Начинайте каждую сессию Space Run с полным щитом.',
        'icon': 'ShieldCheck',
        'tier': 'common',
        'category': 'game',
        'cost': 30,
        'features': ['Full Shield Start', '+50% Survival', 'More Stars', 'All Sessions'],
        'order': 1,
    },
    {
        'slug': 'space-run-magnet-boost',
        'title_en': 'Space Run: Magnet Boost',
        'title_uz': 'Space Run: Magnit Kuchaytirgich',
        'title_ru': 'Space Run: Магнит Усилитель',
        'description_en': 'Activate a permanent magnet field that pulls energy cores toward your ship automatically.',
        'description_uz': "Energiya yadrolari kemaningizga avtomatik tortadigan doimiy magnit maydonini faollashtiring.",
        'description_ru': 'Активируйте постоянное магнитное поле для автоматического притяжения энергоядер.',
        'icon': 'Sparkles',
        'tier': 'rare',
        'category': 'game',
        'cost': 80,
        'features': ['Auto-Collect Cores', 'Permanent Effect', '2x Energy', 'Stack with Boosts'],
        'order': 2,
    },
    {
        'slug': 'astronomy-mock-test',
        'title_en': 'Astronomy Mock Exam',
        'title_uz': 'Astronomiya Sinov Imtihoni',
        'title_ru': 'Пробный Экзамен по Астрономии',
        'description_en': 'Full-length simulated astronomy exam with 50 questions covering solar systems, galaxies, and cosmology.',
        'description_uz': "Quyosh tizimlari, galaktikalar va kosmologiyani qamrab oluvchi 50 ta savoldan iborat to'liq astronomiya imtihoni.",
        'description_ru': 'Полноценный пробный экзамен по астрономии из 50 вопросов.',
        'icon': 'GraduationCap',
        'tier': 'common',
        'category': 'tests',
        'cost': 50,
        'features': ['50 Questions', '90 min Timer', 'Auto-Scoring', 'Detailed Results'],
        'order': 3,
    },
    {
        'slug': 'physics-mock-test',
        'title_en': 'Physics Challenge Exam',
        'title_uz': 'Fizika Challenge Imtihoni',
        'title_ru': 'Экзамен-Челлендж по Физике',
        'description_en': 'Advanced physics problems covering mechanics, thermodynamics, and astrophysics. Timed exam with band scoring.',
        'description_uz': "Mexanika, termodinamika va astrofizikani qamrab oluvchi murakkab fizika masalalari.",
        'description_ru': 'Продвинутые задачи по физике: механика, термодинамика и астрофизика.',
        'icon': 'Zap',
        'tier': 'rare',
        'category': 'tests',
        'cost': 120,
        'features': ['40 Problems', 'Olympiad Level', '120 min', 'Score Analysis'],
        'order': 4,
    },
    {
        'slug': 'mentor-code-review',
        'title_en': 'Mentor Code Review',
        'title_uz': 'Mentor Kod Tekshiruvi',
        'title_ru': 'Менторская Проверка Кода',
        'description_en': 'Submit your project code for a professional review by an experienced developer. Line-by-line feedback and best practices.',
        'description_uz': "Loyiha kodingizni tajribali dasturchi tomonidan professional tekshiruvga yuboring.",
        'description_ru': 'Отправьте код проекта на профессиональную проверку опытным разработчиком.',
        'icon': 'Code2',
        'tier': 'epic',
        'category': 'mentor',
        'cost': 300,
        'features': ['1 Project Review', 'Line-by-line', 'Best Practices', '48h Turnaround'],
        'order': 5,
    },
    {
        'slug': 'mentor-portfolio-consult',
        'title_en': 'Portfolio Consultation',
        'title_uz': 'Portfolio Konsultatsiyasi',
        'title_ru': 'Консультация по Портфолио',
        'description_en': 'One-on-one session with a mentor to polish your developer portfolio and GitHub profile for job applications.',
        'description_uz': "Ish arizalari uchun dasturchi portfolio va GitHub profilingizni takomillashtirish bo'yicha mentorlik sessiyasi.",
        'description_ru': 'Индивидуальная сессия с ментором для подготовки портфолио и GitHub профиля.',
        'icon': 'MessageSquare',
        'tier': 'epic',
        'category': 'mentor',
        'cost': 400,
        'features': ['1-on-1 Session', 'GitHub Review', 'Resume Tips', 'Action Plan'],
        'order': 6,
    },
    {
        'slug': 'advanced-algo-pack',
        'title_en': 'Advanced Algorithm Pack',
        'title_uz': 'Murakkab Algoritmlar Paketi',
        'title_ru': 'Пакет Продвинутых Алгоритмов',
        'description_en': 'Unlock 50 elite algorithmic challenges covering dynamic programming, graph theory, and competitive coding.',
        'description_uz': "Dinamik dasturlash, graf nazariyasi va musobaqa kodlashni qamrab oluvchi 50 ta elit algoritmik masalalarni oching.",
        'description_ru': 'Откройте 50 элитных алгоритмических задач: DP, графы и соревновательное программирование.',
        'icon': 'Zap',
        'tier': 'rare',
        'category': 'content',
        'cost': 200,
        'features': ['50 Problems', 'DP + Graphs', 'Solutions', 'Complexity Analysis'],
        'order': 7,
    },
    {
        'slug': 'masterclass-system-design',
        'title_en': 'Masterclass: System Design',
        'title_uz': 'Masterklass: Tizim Dizayni',
        'title_ru': 'Мастеркласс: Проектирование Систем',
        'description_en': 'Exclusive video masterclass series on designing scalable systems — from monolith to distributed architecture.',
        'description_uz': "Masshtabli tizimlarni loyihalash bo'yicha eksklyuziv video masterklass seriyasi.",
        'description_ru': 'Эксклюзивная серия видео-мастерклассов по проектированию масштабируемых систем.',
        'icon': 'Crown',
        'tier': 'legendary',
        'category': 'content',
        'cost': 800,
        'features': ['12 Videos', 'Case Studies', 'Diagrams', 'Certificate'],
        'order': 8,
    },
    {
        'slug': 'space-run-double-stars',
        'title_en': 'Space Run: Double Stars',
        'title_uz': 'Space Run: Ikki Baravar Yulduzlar',
        'title_ru': 'Space Run: Двойные Звёзды',
        'description_en': 'Double the arcade stars earned from every Space Run session. Stack your rewards twice as fast!',
        'description_uz': "Har bir Space Run sessiyasidan olingan arkada yulduzlarini ikki baravar ko'paytiring.",
        'description_ru': 'Удвойте звёзды за каждую сессию Space Run!',
        'icon': 'Star',
        'tier': 'epic',
        'category': 'game',
        'cost': 250,
        'features': ['2x Stars', 'All Sessions', 'Permanent', 'More Ship Skins'],
        'order': 9,
    },
    {
        'slug': 'interview-simulator',
        'title_en': 'AI Interview Simulator',
        'title_uz': 'AI Intervyu Simulyatori',
        'title_ru': 'AI Симулятор Собеседования',
        'description_en': 'Practice technical and behavioral interviews with an AI interviewer. Get real-time feedback and scoring.',
        'description_uz': "AI intervyuer bilan texnik va xulq-atvor intervyularini mashq qiling.",
        'description_ru': 'Практикуйте технические и поведенческие собеседования с AI интервьюером.',
        'icon': 'Trophy',
        'tier': 'rare',
        'category': 'tests',
        'cost': 150,
        'features': ['AI Interviewer', 'Tech + Behavioral', 'Real-time Feedback', 'Score Report'],
        'order': 10,
    },
]

for p in products:
    obj, created = RewardProduct.objects.update_or_create(slug=p['slug'], defaults=p)
    status = 'Created' if created else 'Updated'
    print(f"  {status}: {p['title_en']} ({p['tier']}) — {p['cost']} coins")

print(f"\nDone! {len(products)} reward products seeded.")
