# Generated by Django 6.0 on 2026-04-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('description_en', models.TextField()),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('launch', 'Launch'), ('mission', 'Mission'), ('discovery', 'Discovery'), ('milestone', 'Milestone'), ('anniversary', 'Anniversary'), ('observation', 'Observation')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('source_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_historical', models.BooleanField(default=False, help_text='Show in History timeline')),
            ],
            options={
                'verbose_name': 'Space Event',
                'ordering': ['event_date'],
            },
        ),
    ]
