# Generated by Django 6.0 on 2026-08-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_spacevent_extras'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='spaceevent',
            index=models.Index(fields=['event_type', 'event_date'], name='event_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceevent',
            index=models.Index(fields=['is_featured', 'event_date'], name='event_featured_date_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceevent',
            index=models.Index(fields=['is_historical', 'event_date'], name='event_historical_date_idx'),
        ),
    ]
