# Generated by Django 6.0 on 2026-08-22 08:03

import apps.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_cache_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.validators.image_upload_to('avatars')),
        ),
    ]
