# Generated by Django 6.0 on 2026-04-29 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
                ('item_type', models.CharField(choices=[('spaceship', 'Spaceship'), ('badge', 'Badge'), ('boost', 'XP Boost')], max_length=20)),
                ('cost_fuel', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='market/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Market Item',
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Inventory',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
