# Generated by Django 6.0 on 2026-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Discount percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='original_price',
            field=models.PositiveIntegerField(blank=True, help_text='Original price before discount (leave blank if no discount)', null=True),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Price in soums'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='cost_fuel',
            field=models.PositiveIntegerField(help_text='Price in fuel (gamification currency)'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='item_type',
            field=models.CharField(choices=[('spaceship', 'Spaceship'), ('badge', 'Badge'), ('boost', 'XP Boost'), ('book', 'Book'), ('rocket_module', 'Rocket Module'), ('satellite', 'Satellite'), ('other', 'Other')], max_length=20),
        ),
    ]
