# Generated by Django 6.0 on 2026-04-30 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketitem_discount_percent_marketitem_is_bestseller_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=80)),
                ('name_uz', models.CharField(max_length=80)),
                ('name_ru', models.CharField(blank=True, default='', max_length=80)),
                ('icon', models.CharField(blank=True, default='Package', help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(blank=True, default='#a78bfa', max_length=24)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='marketitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Market Item'},
        ),
        migrations.AddField(
            model_name='marketitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketitem',
            name='discount_end',
            field=models.DateTimeField(blank=True, help_text='When discount expires', null=True),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='discount_start',
            field=models.DateTimeField(blank=True, help_text='When discount becomes active', null=True),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage / featured section'),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='is_limited',
            field=models.BooleanField(default=False, help_text='Limited edition item'),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='rating_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Discount 0-100'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='item_type',
            field=models.CharField(choices=[('spaceship', 'Spaceship'), ('badge', 'Badge'), ('boost', 'XP Boost'), ('book', 'Book'), ('rocket_module', 'Rocket Module'), ('satellite', 'Satellite'), ('avatar', 'Avatar'), ('theme', 'Theme'), ('tool', 'Tool'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='original_price',
            field=models.PositiveIntegerField(blank=True, help_text='Original price before discount', null=True),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='market.marketcategory'),
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5 stars')),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market.marketitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Review',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
