# Generated by Django 6.0 on 2026-08-22 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_marketcategory_alter_marketitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreview',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
