# Generated by Django 6.0 on 2026-08-22 08:03

import apps.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_review_rating_bounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.validators.image_upload_to('market')),
        ),
    ]
