# Generated by Django 6.0 on 2026-04-29 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('order', models.PositiveSmallIntegerField()),
                ('title_en', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('lesson_type', models.CharField(choices=[('explanation', 'Explanation'), ('quiz', 'Quiz'), ('video', 'Video'), ('simulation', 'Simulation')], max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Lesson',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('title_en', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Level',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('section_type', models.CharField(max_length=20)),
                ('content_en', models.JSONField(default=dict)),
                ('content_uz', models.JSONField(default=dict)),
                ('content_ru', models.JSONField(default=dict)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text_en', models.TextField()),
                ('text_uz', models.TextField()),
                ('text_ru', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=1)),
                ('explanation_en', models.TextField()),
                ('explanation_uz', models.TextField()),
                ('explanation_ru', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('order', models.PositiveSmallIntegerField()),
                ('title_en', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('fuel_reward', models.PositiveIntegerField(default=50)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.level')),
            ],
            options={
                'verbose_name': 'Unit',
                'ordering': ['order'],
                'unique_together': {('level', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('unit', 'slug')},
        ),
    ]
