# Generated by Django 6.0 on 2026-04-30 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-safe identifier, e.g. "physics"', unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(help_text='Display title (Uzbek)', max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('title_ru', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#a78bfa', help_text='Hex color for UI', max_length=24)),
                ('icon', models.CharField(default='BookOpen', help_text='Lucide icon name', max_length=50)),
                ('link', models.CharField(blank=True, default='', help_text='Frontend route, e.g. /learn/physics', max_length=120)),
                ('lessons_count', models.PositiveIntegerField(default=0, help_text='Cached count for card display')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sphere',
                'verbose_name_plural': 'Spheres',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, default='', max_length=200)),
                ('title_ru', models.CharField(blank=True, default='', max_length=200)),
                ('color', models.CharField(blank=True, default='', max_length=24)),
                ('description', models.TextField(blank=True, default='')),
                ('sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.sphere')),
            ],
            options={
                'verbose_name': 'Topic',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopicLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=300)),
                ('name_en', models.CharField(blank=True, default='', max_length=300)),
                ('name_ru', models.CharField(blank=True, default='', max_length=300)),
                ('video_url', models.URLField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='', help_text='Lesson text/markdown content')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.topic')),
            ],
            options={
                'verbose_name': 'Topic Lesson',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=300)),
                ('name_en', models.CharField(blank=True, default='', max_length=300)),
                ('name_ru', models.CharField(blank=True, default='', max_length=300)),
                ('video_url', models.URLField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('parent_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_lessons', to='courses.topiclesson')),
            ],
            options={
                'verbose_name': 'Sub-Lesson',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Problem number for display')),
                ('question', models.TextField()),
                ('question_en', models.TextField(blank=True, default='')),
                ('question_ru', models.TextField(blank=True, default='')),
                ('answer', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True, default='')),
                ('explanation_en', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=12)),
                ('sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='courses.sphere')),
            ],
            options={
                'verbose_name': 'Problem',
                'ordering': ['number'],
                'unique_together': {('sphere', 'number')},
            },
        ),
    ]
