# Generated by Django 6.0 on 2026-08-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_adr0001_one_content_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, help_text='Stable identifier, e.g. "physics-kinematika". Seeds key on this. Derived from the English title when left empty.', max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='topiclesson',
            name='slug',
            field=models.SlugField(blank=True, help_text='Stable identifier. Progress and awards key on this, not on (parent, order). Derived from the English name when left empty.', max_length=200, unique=True),
        ),
    ]
