# Generated by Django 6.0 on 2026-04-29 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('summary_en', models.TextField()),
                ('summary_uz', models.TextField()),
                ('summary_ru', models.TextField()),
                ('content_en', models.TextField(blank=True)),
                ('content_uz', models.TextField(blank=True)),
                ('content_ru', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='news/')),
                ('category', models.CharField(choices=[('discovery', 'Discovery'), ('technology', 'Technology'), ('exploration', 'Exploration'), ('local', 'Local'), ('science', 'Science'), ('mission', 'Mission')], default='science', max_length=30)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'ordering': ['-published_at'],
            },
        ),
    ]
