# Generated by Django 6.0 on 2026-08-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['is_published', '-published_at'], name='news_published_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['category', '-published_at'], name='news_category_recent_idx'),
        ),
    ]
