# Generated by Django 6.0 on 2026-04-29 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('condition_type', models.CharField(choices=[('xp_threshold', 'XP Threshold'), ('streak', 'Streak Days'), ('lessons', 'Lessons Completed')], max_length=30)),
                ('condition_value', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Badge',
            },
        ),
        migrations.CreateModel(
            name='UserGamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('fuel', models.PositiveIntegerField(default=100)),
                ('streak', models.PositiveSmallIntegerField(default=0)),
                ('last_play_date', models.DateField(blank=True, null=True)),
                ('skills', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gamification Profile',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
