# Generated by Django 6.0 on 2026-04-30 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_badge_rarity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=150)),
                ('title_uz', models.CharField(blank=True, default='', max_length=150)),
                ('title_ru', models.CharField(blank=True, default='', max_length=150)),
                ('description_en', models.TextField()),
                ('description_uz', models.TextField(blank=True, default='')),
                ('description_ru', models.TextField(blank=True, default='')),
                ('icon', models.CharField(choices=[('BookOpen', 'BookOpen'), ('Code2', 'Code2'), ('GraduationCap', 'GraduationCap'), ('MessageSquare', 'MessageSquare'), ('Trophy', 'Trophy'), ('Zap', 'Zap'), ('Crown', 'Crown'), ('Rocket', 'Rocket'), ('Gamepad2', 'Gamepad2'), ('Star', 'Star'), ('Sparkles', 'Sparkles'), ('ShieldCheck', 'ShieldCheck')], default='Star', max_length=30)),
                ('tier', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('category', models.CharField(choices=[('tests', 'Mock Tests'), ('mentor', 'Mentorship'), ('content', 'Premium Content'), ('game', 'Game Items')], default='content', max_length=20)),
                ('cost', models.PositiveIntegerField(default=50, help_text='Cost in coins (fuel)')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature strings, e.g. ["3 Passages","40 Questions"]')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reward Product',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRewardPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='gamification.rewardproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Reward Purchase',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
