# Generated by Django 6.0 on 2026-05-01 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_rewardproduct_userrewardpurchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=150)),
                ('title_uz', models.CharField(blank=True, default='', max_length=150)),
                ('title_ru', models.CharField(blank=True, default='', max_length=150)),
                ('description_en', models.TextField()),
                ('description_uz', models.TextField(blank=True, default='')),
                ('description_ru', models.TextField(blank=True, default='')),
                ('mission_type', models.CharField(choices=[('streak', 'Daily Streak'), ('lesson', 'Lessons Completed'), ('mastery', 'Lessons Mastered'), ('inventory', 'Shop Items Owned'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('target_value', models.PositiveIntegerField(default=1, help_text='How many actions required (e.g., 2 items)')),
                ('reward_xp', models.PositiveIntegerField(default=0)),
                ('reward_fuel', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_daily', models.BooleanField(default=False, help_text='If True, mission resets daily')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mission',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('last_claimed_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='gamification.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Mission',
                'unique_together': {('user', 'mission')},
            },
        ),
    ]
