# Generated by Django 6.0 on 2026-08-22 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grandfather_existing_conversations(apps, schema_editor):
    """Conversations that already existed predate the consent step.

    They default to `pending`, which would show both sides a request to accept a
    conversation they have been having for weeks. Anything with a message in it
    was already consented to in practice.
    """
    Conversation = apps.get_model('chat', 'Conversation')
    Conversation.objects.filter(messages__isnull=False).distinct().update(status='accepted')


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_directmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('abuse', 'Abusive or threatening'), ('sexual', 'Sexual content'), ('bullying', 'Bullying or harassment'), ('personal_info', 'Sharing personal information'), ('spam', 'Spam or advertising'), ('other', 'Something else')], max_length=20)),
                ('detail', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Message Report',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Block',
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='initiator',
            field=models.ForeignKey(blank=True, help_text='Who asked to start it. The other side is the one who accepts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting the recipient'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='deleted_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', '-created_at'], name='chat_chatme_room_id_df087f_idx'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='chat_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='direct_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.directmessage'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('chat_message__isnull', False), ('direct_message__isnull', True)), models.Q(('chat_message__isnull', True), ('direct_message__isnull', False)), _connector='OR'), name='report_targets_exactly_one_message'),
        ),
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.UniqueConstraint(condition=models.Q(('chat_message__isnull', False)), fields=('reporter', 'chat_message'), name='one_report_per_reporter_per_chat_message'),
        ),
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.UniqueConstraint(condition=models.Q(('direct_message__isnull', False)), fields=('reporter', 'direct_message'), name='one_report_per_reporter_per_direct_message'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocker', 'blocked'], name='chat_userbl_blocker_343807_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together={('blocker', 'blocked')},
        ),
        migrations.RunPython(
            grandfather_existing_conversations, migrations.RunPython.noop,
        ),
    ]
