# Generated by Django 6.0 on 2026-08-22 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_b1_moderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until', models.DateTimeField(help_text='Posting is refused until this moment.')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifted_at', models.DateTimeField(blank=True, help_text='Set when a moderator ends it early.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_suspensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Suspension',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'until'], name='chat_chatsu_user_id_f141e0_idx')],
            },
        ),
    ]
